print("Bienvenue a ce créateur de jeu dont vous etes le héro !. Vous pouvez créer un jeu style RPG !" /n, "Commencons par le debut, determinons les stats de debut des personnages sans bonus :" )
agi=int(input("Pour agilité ? (agi)"))
def=int(input("Pour défense ? (def)"))
strength=int(input("Pour strength ? (str)"))
luck=int(input("Pour luck ? (luck)"))
health=int(input("Pour health ? (HP)")
