import tkinter as tk

def reloadmenu():
    Frame1.destroy()
    Frame2.destroy()
    Label2.destroy()

    Button1 = tk.Button(top)
    Button1.place(relx=0.156, rely=0.375, height=94, width=187)
    Button1.configure(activebackground="#ececec")
    Button1.configure(activeforeground="#000000")
    Button1.configure(background="#d9d9d9")
    Button1.configure(disabledforeground="#a3a3a3")
    Button1.configure(font="-family {Segoe UI} -size 14 -underline 1")
    Button1.configure(foreground="#000000")
    Button1.configure(highlightbackground="#d9d9d9")
    Button1.configure(highlightcolor="black")
    Button1.configure(pady="0")
    Button1.configure(text='''Nouvelle partie''')

    Button2 = tk.Button(top)
    Button2.place(relx=0.547, rely=0.375, height=94, width=187)
    Button2.configure(activebackground="#ececec")
    Button2.configure(activeforeground="#000000")
    Button2.configure(background="#d9d9d9")
    Button2.configure(disabledforeground="#a3a3a3")
    Button2.configure(font="-family {Segoe UI} -size 14")
    Button2.configure(foreground="#000000")
    Button2.configure(highlightbackground="#d9d9d9")
    Button2.configure(highlightcolor="black")
    Button2.configure(pady="0")
    Button2.configure(text='''Charger une partie''')


top = tk.Tk()
top.geometry("640x450+468+138")
top.minsize(120, 1)
top.maxsize(1540, 845)
top.resizable(1,  1)
top.title("New Toplevel")
top.configure(background="#bff2c7")

Frame1 = tk.Frame(top)
Frame1.place(relx=0.033, rely=0.044, relheight=0.233 , relwidth=0.942)
Frame1.configure(relief='groove')
Frame1.configure(borderwidth="2")
Frame1.configure(relief="groove")
Frame1.configure(background="#80e1a7")

Label1 = tk.Label(Frame1)
Label1.place(relx=0.017, rely=0.133, height=71, width=574)
Label1.configure(background="#80e1a7")
Label1.configure(disabledforeground="#a3a3a3")
Label1.configure(font="-family {Forte} -size 24 -weight bold -underline 1")
Label1.configure(foreground="#000000")
Label1.configure(highlightbackground="#f0f0f0f0f0f0")
Label1.configure(text='''Bienvenue sur DualCent''')

Frame2 = tk.Frame(top)
Frame2.place(relx=0.031, rely=0.289, relheight=0.567   , relwidth=0.945)
Frame2.configure(relief='groove')
Frame2.configure(borderwidth="2")
Frame2.configure(relief="groove")
Frame2.configure(background="#80e1a7")

Button1 = tk.Button(Frame2, command=reloadmenu)
Button1.place(relx=0.083, rely=0.353, height=54, width=107)
Button1.configure(activebackground="#ececec")
Button1.configure(activeforeground="#000000")
Button1.configure(background="#85b90b")
Button1.configure(disabledforeground="#a3a3a3")
Button1.configure(foreground="#000000")
Button1.configure(highlightbackground="#d9d9d9")
Button1.configure(highlightcolor="black")
Button1.configure(pady="0")
Button1.configure(text='''JOUER''')

Button2 = tk.Button(Frame2)
Button2.place(relx=0.413, rely=0.353, height=54, width=107)
Button2.configure(activebackground="#ececec")
Button2.configure(activeforeground="#000000")
Button2.configure(background="#85b90b")
Button2.configure(disabledforeground="#a3a3a3")
Button2.configure(foreground="#000000")
Button2.configure(highlightbackground="#d9d9d9")
Button2.configure(highlightcolor="black")
Button2.configure(pady="0")
Button2.configure(text='''EDITER''')

Button3 = tk.Button(Frame2,command=top.quit)
Button3.place(relx=0.744, rely=0.353, height=54, width=107)
Button3.configure(activebackground="#ececec")
Button3.configure(activeforeground="#000000")
Button3.configure(background="#85b90b")
Button3.configure(disabledforeground="#a3a3a3")
Button3.configure(foreground="#000000")
Button3.configure(highlightbackground="#d9d9d9")
Button3.configure(highlightcolor="black")
Button3.configure(pady="0")
Button3.configure(text='''QUITTER''')

Label2 = tk.Label(top)
Label2.place(relx=0.719, rely=0.889, height=41, width=174)
Label2.configure(background="#bff2c7")
Label2.configure(disabledforeground="#a3a3a3")
Label2.configure(foreground="#000000")
Label2.configure(text='''Crée par Rasputin Team''')

menu_bar = tk.Menu(top)
file_menu = tk.Menu(menu_bar, tearoff=0) #création du menu en haut de la page
file_menu.add_command(label="Quitter", command=top.quit)
menu_bar.add_cascade(label="Fichier", menu=file_menu)
top.config(menu=menu_bar)

top.mainloop()
